import type { EventBoard, EventRecord, Idea, Profile, Team, TeamMember } from "@/lib/types";

const eventId = "11111111-1111-4111-8111-111111111111";

const now = "2026-06-14T12:00:00.000Z";

export const demoEvent: EventRecord = {
  id: eventId,
  slug: "world-cup-hack",
  name: "World Cup Hack",
  location: "Innovation Arena",
  starts_at: "2026-06-20T14:00:00.000Z",
  organizer_email: "organizer@scoutboard.dev",
  premium_until: null,
  created_at: now,
};

export const demoProfiles: Profile[] = [
  {
    id: "22222222-2222-4222-8222-222222222201",
    event_id: eventId,
    user_id: null,
    name: "Maya Chen",
    email: "maya@example.com",
    linkedin_url: "https://www.linkedin.com/in/mayachen",
    avatar_url: null,
    headline: "Full-stack captain who ships polished demos",
    bio: "Builds fast product loops with React, Supabase, and crisp demo storytelling.",
    skills: ["React", "Next.js", "Supabase", "Product"],
    positions: ["Frontend", "Full-stack"],
    interests: ["AI agents", "Civic tech", "Developer tools"],
    wants_to_build: "A scout that helps hackathon teams find missing positions quickly.",
    has_idea: true,
    looking_for_team: false,
    vibe: "trying-to-win",
    experience_level: "advanced",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222202",
    event_id: eventId,
    user_id: null,
    name: "Jordan Patel",
    email: "jordan@example.com",
    linkedin_url: null,
    avatar_url: null,
    headline: "Designer who turns messy concepts into clear flows",
    bio: "Loves service design, pitch decks, and product experiences that feel ready by Sunday.",
    skills: ["UX", "Figma", "Brand", "Pitch"],
    positions: ["Design", "Product"],
    interests: ["Health", "Education", "Consumer apps"],
    wants_to_build: "Tools that reduce stress for first-time hackers.",
    has_idea: false,
    looking_for_team: true,
    vibe: "beginner-friendly",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222203",
    event_id: eventId,
    user_id: null,
    name: "Sam Rivera",
    email: "sam@example.com",
    linkedin_url: null,
    avatar_url: null,
    headline: "ML midfielder with pragmatic model taste",
    bio: "Turns ambiguous AI ideas into scoped workflows, evals, and working endpoints.",
    skills: ["Python", "OpenAI", "Embeddings", "Evaluation"],
    positions: ["AI/ML", "Backend"],
    interests: ["Search", "Sports tech", "Knowledge tools"],
    wants_to_build: "A recommendation system that explains why teammates match.",
    has_idea: false,
    looking_for_team: true,
    vibe: "serious",
    experience_level: "advanced",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222204",
    event_id: eventId,
    user_id: null,
    name: "Ava Brooks",
    email: "ava@example.com",
    linkedin_url: null,
    avatar_url: null,
    headline: "Backend keeper for payments, auth, and reliable APIs",
    bio: "Comfortable with Supabase, Stripe, email workflows, and security tradeoffs.",
    skills: ["Postgres", "Stripe", "RLS", "Node.js"],
    positions: ["Backend", "Infrastructure"],
    interests: ["Fintech", "Marketplaces", "Ops tools"],
    wants_to_build: "A product teams can actually operate after demo day.",
    has_idea: false,
    looking_for_team: true,
    vibe: "serious",
    experience_level: "advanced",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222205",
    event_id: eventId,
    user_id: null,
    name: "Noah Kim",
    email: "noah@example.com",
    linkedin_url: null,
    avatar_url: null,
    headline: "Mobile striker who likes fast prototypes",
    bio: "Ships mobile-first interfaces, maps, and playful interaction details.",
    skills: ["React Native", "Maps", "Animations", "TypeScript"],
    positions: ["Mobile", "Frontend"],
    interests: ["Travel", "Sports", "Local discovery"],
    wants_to_build: "A live city guide for fans visiting new stadiums.",
    has_idea: true,
    looking_for_team: false,
    vibe: "chill",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222206",
    event_id: eventId,
    user_id: null,
    name: "Lina Okafor",
    email: "lina@example.com",
    linkedin_url: null,
    avatar_url: null,
    headline: "Data winger for dashboards and decision loops",
    bio: "Finds the signal in event data and turns it into simple, visual workflows.",
    skills: ["Analytics", "SQL", "Charts", "PostHog"],
    positions: ["Data", "Product"],
    interests: ["Climate", "Events", "Communities"],
    wants_to_build: "A dashboard that helps organizers keep teams balanced in real time.",
    has_idea: false,
    looking_for_team: true,
    vibe: "trying-to-win",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
];

export const demoIdeas: Idea[] = [
  {
    id: "33333333-3333-4333-8333-333333333301",
    event_id: eventId,
    owner_profile_id: demoProfiles[0].id,
    title: "ScoutBoard",
    one_liner: "A live transfer market that helps hackers form balanced teams before momentum dies.",
    target_user: "Hackathon participants and organizers",
    roles_needed: ["AI/ML", "Backend", "Design"],
    tags: ["AI agents", "Marketplaces", "Events"],
    vibe: "trying-to-win",
    status: "open",
    created_at: now,
    updated_at: now,
  },
  {
    id: "33333333-3333-4333-8333-333333333302",
    event_id: eventId,
    owner_profile_id: demoProfiles[4].id,
    title: "FanTrail",
    one_liner: "A mobile match-day guide that turns city exploration into a fan challenge.",
    target_user: "Traveling sports fans",
    roles_needed: ["Design", "Backend", "Data"],
    tags: ["Sports tech", "Travel", "Consumer apps"],
    vibe: "chill",
    status: "open",
    created_at: now,
    updated_at: now,
  },
  {
    id: "33333333-3333-4333-8333-333333333303",
    event_id: eventId,
    owner_profile_id: demoProfiles[5].id,
    title: "GreenRoom Ops",
    one_liner: "A lightweight command center for organizers balancing volunteers, rooms, and teams.",
    target_user: "Hackathon organizers",
    roles_needed: ["Frontend", "Backend", "Product"],
    tags: ["Ops tools", "Events", "Analytics"],
    vibe: "serious",
    status: "open",
    created_at: now,
    updated_at: now,
  },
];

export const demoTeams: Team[] = [
  {
    id: "44444444-4444-4444-8444-444444444401",
    event_id: eventId,
    owner_profile_id: demoProfiles[0].id,
    idea_id: demoIdeas[0].id,
    name: "ScoutBoard FC",
    tagline: "The transfer desk for balanced hackathon squads.",
    vibe: "trying-to-win",
    roles_needed: ["AI/ML", "Backend", "Design"],
    max_size: 4,
    status: "forming",
    created_at: now,
    updated_at: now,
  },
  {
    id: "44444444-4444-4444-8444-444444444402",
    event_id: eventId,
    owner_profile_id: demoProfiles[4].id,
    idea_id: demoIdeas[1].id,
    name: "FanTrail United",
    tagline: "City discovery for match-day supporters.",
    vibe: "chill",
    roles_needed: ["Design", "Backend", "Data"],
    max_size: 4,
    status: "forming",
    created_at: now,
    updated_at: now,
  },
  {
    id: "44444444-4444-4444-8444-444444444403",
    event_id: eventId,
    owner_profile_id: demoProfiles[5].id,
    idea_id: demoIdeas[2].id,
    name: "GreenRoom City",
    tagline: "Organizer visibility from kickoff to judging.",
    vibe: "serious",
    roles_needed: ["Frontend", "Backend", "Product"],
    max_size: 4,
    status: "forming",
    created_at: now,
    updated_at: now,
  },
];

export const demoTeamMembers: TeamMember[] = [
  {
    id: "55555555-5555-4555-8555-555555555501",
    team_id: demoTeams[0].id,
    profile_id: demoProfiles[0].id,
    role: "Captain / Full-stack",
    created_at: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555502",
    team_id: demoTeams[0].id,
    profile_id: demoProfiles[3].id,
    role: "Backend",
    created_at: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555503",
    team_id: demoTeams[1].id,
    profile_id: demoProfiles[4].id,
    role: "Captain / Mobile",
    created_at: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555504",
    team_id: demoTeams[2].id,
    profile_id: demoProfiles[5].id,
    role: "Captain / Data",
    created_at: now,
  },
];

export const demoEventBoard: EventBoard = {
  event: demoEvent,
  profiles: demoProfiles,
  ideas: demoIdeas,
  teams: demoTeams,
  team_members: demoTeamMembers,
  join_requests: [],
};

export function getDemoBoard(slug: string) {
  if (slug === demoEvent.slug) {
    return demoEventBoard;
  }

  return null;
}

export function createEmptyBoard(slug: string): EventBoard {
  return {
    event: {
      id: "00000000-0000-4000-8000-000000000000",
      slug,
      name: slug
        .split("-")
        .filter(Boolean)
        .map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`)
        .join(" ") || "ScoutBoard Event",
      location: null,
      starts_at: null,
      organizer_email: null,
      premium_until: null,
      created_at: now,
    },
    profiles: [],
    ideas: [],
    teams: [],
    team_members: [],
    join_requests: [],
  };
}
