import type { EventBoard, EventRecord, Idea, Profile, Team, TeamMember } from "@/lib/types";

/** Sentinel id for the synthetic board returned for unknown slugs. */
export const EMPTY_EVENT_ID = "00000000-0000-4000-8000-000000000000";

const eventId = "11111111-1111-4111-8111-111111111111";

const now = "2026-06-14T12:00:00.000Z";

export const demoEvent: EventRecord = {
  id: eventId,
  slug: "world-cup-hack",
  name: "World Cup Hack",
  location: "Innovation Arena",
  starts_at: "2026-06-20T14:00:00.000Z",
  organizer_email: "organizer@formation.dev",
  premium_until: null,
  created_at: now,
};

export const demoProfiles: Profile[] = [
  {
    id: "22222222-2222-4222-8222-222222222201",
    event_id: eventId,
    user_id: null,
    name: "Maya Chen",
    email: null,
    linkedin_url: "https://www.linkedin.com/in/mayachen",
    avatar_url: null,
    headline: "Full-stack builder who ships polished demos",
    bio: "Builds fast product loops with React, Supabase, and crisp demo storytelling.",
    skills: ["frontend", "backend", "deployment", "product"],
    positions: ["frontend", "backend", "full-stack"],
    interests: ["AI agents", "developer tools", "events"],
    wants_to_build: "A scout that helps hackathon teams find missing positions quickly.",
    has_idea: true,
    looking_for_team: false,
    vibe: "trying-to-win",
    experience_level: "advanced",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222202",
    event_id: eventId,
    user_id: null,
    name: "Jordan Patel",
    email: null,
    linkedin_url: null,
    avatar_url: null,
    headline: "Designer who turns messy concepts into clear flows",
    bio: "Loves service design, pitch decks, and product experiences that feel ready by Sunday.",
    skills: ["design", "product", "pitch"],
    positions: ["designer", "product", "pitch"],
    interests: ["health", "education", "consumer apps"],
    wants_to_build: "Tools that reduce stress for first-time hackers.",
    has_idea: false,
    looking_for_team: true,
    vibe: "beginner-friendly",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222203",
    event_id: eventId,
    user_id: null,
    name: "Sam Rivera",
    email: null,
    linkedin_url: null,
    avatar_url: null,
    headline: "ML midfielder with pragmatic model taste",
    bio: "Turns ambiguous AI ideas into scoped workflows, evals, and working endpoints.",
    skills: ["ML", "backend", "data"],
    positions: ["AI/ML", "backend"],
    interests: ["search", "sports tech", "knowledge tools"],
    wants_to_build: "A recommendation system that explains why teammates match.",
    has_idea: false,
    looking_for_team: true,
    vibe: "serious",
    experience_level: "advanced",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222204",
    event_id: eventId,
    user_id: null,
    name: "Ava Brooks",
    email: null,
    linkedin_url: null,
    avatar_url: null,
    headline: "Backend keeper for payments, auth, and reliable APIs",
    bio: "Comfortable with Supabase, payments, email workflows, and security tradeoffs.",
    skills: ["backend", "payments", "deployment"],
    positions: ["backend", "full-stack"],
    interests: ["marketplaces", "ops tools"],
    wants_to_build: "A product teams can actually operate after demo day.",
    has_idea: false,
    looking_for_team: true,
    vibe: "serious",
    experience_level: "advanced",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222205",
    event_id: eventId,
    user_id: null,
    name: "Noah Kim",
    email: null,
    linkedin_url: null,
    avatar_url: null,
    headline: "Mobile striker who likes fast prototypes",
    bio: "Ships mobile-first interfaces, maps, and playful interaction details.",
    skills: ["mobile", "frontend", "deployment"],
    positions: ["frontend", "full-stack"],
    interests: ["travel", "sports", "local discovery"],
    wants_to_build: "A live city guide for fans visiting new stadiums.",
    has_idea: true,
    looking_for_team: false,
    vibe: "chill",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222206",
    event_id: eventId,
    user_id: null,
    name: "Lina Okafor",
    email: null,
    linkedin_url: null,
    avatar_url: null,
    headline: "Data winger for dashboards and decision loops",
    bio: "Finds the signal in event data and turns it into simple, visual workflows.",
    skills: ["data", "product", "frontend"],
    positions: ["product", "frontend"],
    interests: ["climate", "events", "communities"],
    wants_to_build: "A dashboard that helps organizers keep teams balanced in real time.",
    has_idea: false,
    looking_for_team: true,
    vibe: "trying-to-win",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222207",
    event_id: eventId,
    user_id: null,
    name: "Priya Shah",
    email: null,
    linkedin_url: null,
    avatar_url: null,
    headline: "Pitch lead who sharpens the story under pressure",
    bio: "Turns technical progress into a judging narrative with clear user value.",
    skills: ["pitch", "product", "design"],
    positions: ["pitch", "product"],
    interests: ["social impact", "AI agents"],
    wants_to_build: "A Sunday-ready story for a product people understand immediately.",
    has_idea: false,
    looking_for_team: true,
    vibe: "trying-to-win",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222208",
    event_id: eventId,
    user_id: null,
    name: "Ethan Wright",
    email: null,
    linkedin_url: null,
    avatar_url: null,
    headline: "Deployment-minded builder who keeps demos online",
    bio: "Handles hosting, environment variables, database setup, and the final demo checklist.",
    skills: ["deployment", "backend", "data"],
    positions: ["backend", "full-stack"],
    interests: ["infrastructure", "developer tools"],
    wants_to_build: "A reliable product demo that survives judge traffic.",
    has_idea: false,
    looking_for_team: true,
    vibe: "chill",
    experience_level: "intermediate",
    created_at: now,
    updated_at: now,
  },
];

export const demoIdeas: Idea[] = [
  {
    id: "33333333-3333-4333-8333-333333333301",
    event_id: eventId,
    owner_profile_id: demoProfiles[0].id,
    title: "Formation",
    one_liner: "A live team workspace that helps hackers form balanced groups before momentum dies.",
    target_user: "Hackathon participants and organizers",
    roles_needed: ["AI/ML", "backend", "designer"],
    tags: ["AI agents", "marketplaces", "events"],
    vibe: "trying-to-win",
    status: "open",
    created_at: now,
    updated_at: now,
  },
  {
    id: "33333333-3333-4333-8333-333333333302",
    event_id: eventId,
    owner_profile_id: demoProfiles[4].id,
    title: "FanTrail",
    one_liner: "A mobile match-day guide that turns city exploration into a fan challenge.",
    target_user: "Traveling sports fans",
    roles_needed: ["designer", "backend", "data"],
    tags: ["sports tech", "travel", "consumer apps"],
    vibe: "chill",
    status: "open",
    created_at: now,
    updated_at: now,
  },
  {
    id: "33333333-3333-4333-8333-333333333303",
    event_id: eventId,
    owner_profile_id: demoProfiles[5].id,
    title: "GreenRoom Ops",
    one_liner: "A lightweight command center for organizers balancing volunteers, rooms, and teams.",
    target_user: "Hackathon organizers",
    roles_needed: ["frontend", "backend", "product"],
    tags: ["ops tools", "events", "analytics"],
    vibe: "serious",
    status: "open",
    created_at: now,
    updated_at: now,
  },
];

export const demoTeams: Team[] = [
  {
    id: "44444444-4444-4444-8444-444444444401",
    event_id: eventId,
    owner_profile_id: demoProfiles[0].id,
    idea_id: demoIdeas[0].id,
    name: "Formation Lab",
    tagline: "A workspace for balanced hackathon squads.",
    vibe: "trying-to-win",
    roles_needed: ["AI/ML", "backend", "designer"],
    max_size: 4,
    status: "forming",
    created_at: now,
    updated_at: now,
  },
  {
    id: "44444444-4444-4444-8444-444444444402",
    event_id: eventId,
    owner_profile_id: demoProfiles[4].id,
    idea_id: demoIdeas[1].id,
    name: "FanTrail United",
    tagline: "City discovery for match-day supporters.",
    vibe: "chill",
    roles_needed: ["designer", "backend", "data"],
    max_size: 4,
    status: "forming",
    created_at: now,
    updated_at: now,
  },
];

export const demoTeamMembers: TeamMember[] = [
  {
    id: "55555555-5555-4555-8555-555555555501",
    team_id: demoTeams[0].id,
    profile_id: demoProfiles[0].id,
    role: "Captain / full-stack",
    created_at: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555502",
    team_id: demoTeams[0].id,
    profile_id: demoProfiles[3].id,
    role: "backend",
    created_at: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555503",
    team_id: demoTeams[1].id,
    profile_id: demoProfiles[4].id,
    role: "Captain / mobile",
    created_at: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555504",
    team_id: demoTeams[1].id,
    profile_id: demoProfiles[7].id,
    role: "deployment",
    created_at: now,
  },
];

export const demoEventBoard: EventBoard = {
  event: demoEvent,
  profiles: demoProfiles,
  ideas: demoIdeas,
  teams: demoTeams,
  team_members: demoTeamMembers,
  join_requests: [],
  source: "demo",
};

export function getDemoBoard(slug: string) {
  if (slug === demoEvent.slug) {
    return demoEventBoard;
  }

  return null;
}

export function createEmptyBoard(slug: string): EventBoard {
  return {
    event: {
      id: EMPTY_EVENT_ID,
      slug,
      name:
        slug
          .split("-")
          .filter(Boolean)
          .map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`)
          .join(" ") || "Formation Event",
      location: null,
      starts_at: null,
      organizer_email: null,
      premium_until: null,
      created_at: now,
    },
    profiles: [],
    ideas: [],
    teams: [],
    team_members: [],
    join_requests: [],
    source: "demo",
  };
}
